# Generated by Django 4.1 on 2022-08-06 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Fruits",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fruit_name", models.CharField(max_length=100)),
                ("price", models.IntegerField()),
                ("manufacturing_date", models.DateField()),
                ("fruit_description", models.TextField()),
                ("is_fresh", models.BooleanField(default=True)),
            ],
        ),
    ]
