# Generated by Django 4.1 on 2022-08-06 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="fruits",
            options={"ordering": ["-fruit_name"]},
        ),
        migrations.AlterUniqueTogether(
            name="fruits",
            unique_together={("fruit_name", "price")},
        ),
        migrations.AlterModelTable(
            name="fruits",
            table="home_fruits",
        ),
    ]
