# Generated by Django 4.1 on 2022-08-06 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_alter_fruits_options_alter_fruits_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="fruits",
            options={"ordering": ["-fruit_name"], "verbose_name": "home_fruits"},
        ),
    ]
