# Generated by Django 4.1 on 2022-08-06 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_alter_fruits_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fruits",
            name="fruit_description",
            field=models.TextField(blank=True),
        ),
    ]
